### ISSUE TITLE
Fix compilation issues related to OpenMP on macOS 

### ISSUE THREAD

**Issue by richefeu** [rprat-pro/MATools#1]

**Comment by richefeu** [comment]
Il me semble que tous les #pragma omp dans MATrace/MATrace.cxx ne sont pas nécessaires. Sur mac, ça compile, mais avec des warnings disant que les pragma sont ignorés.
Je ne peux pas faire de pull request...

**Comment by rprat-pro** [comment]
Je pense qu'ils sont ignorés car tu n'as pas compilé avec openmp.
